"""Whiteout — the object table (DR-17a): every authored object as a ROW. This is the authoring
surface for objects (docs/guides/authoring-objects.md). The SAME table feeds the Evennia loader
(`build.py`) and the pure `PureWorld` used by probes and fuzz, so the two can never drift.

Fields: sim_id · name · aliases · materials (primary first) · mass_g (BODY grams, excluding parts) ·
exactly one of `zone` (placed) / `in` (stowed inside a parent — DR-24: found by open/search/dig) ·
state (ident, fixed, container, open, sealed, jammed, wet, lit, ignition, powered, worn_by, form,
authored capabilities like edge/leverage) · parts (id, label, material, mass_g, attachment,
outputs_when_removed). Tunable content. Generated 2026-09-07 from the hand-built loader, then
kept by hand.
"""
from __future__ import annotations

OBJECT_TABLE: list[dict] = [
    # -------------------- cockpit --------------------
    {'sim_id': 'radio',
     'name': 'field radio',
     'aliases': ['radio'],
     'materials': ['plastic', 'copper_wire'],
     'mass_g': 900,
     'zone': 'cockpit',
     'state': {'ident': 'RT-220', 'powered': False, 'fixed': True},
    },
    {'sim_id': 'pilot',
     'name': 'the pilot',
     'aliases': ['pilot', 'body'],
     'materials': ['flesh'],
     'mass_g': 78000,
     'zone': 'cockpit',
     'state': {'dead': True},
    },
    {'sim_id': 'lighter',
     'name': 'lighter',
     'materials': ['plastic'],
     'mass_g': 20,
     'in': 'pilot',
     'state': {'ignition': True},
    },
    {'sim_id': 'jacket',
     'name': 'flight jacket',
     'aliases': ['jacket', 'coat'],
     'materials': ['leather'],
     'mass_g': 1200,
     'in': 'pilot',
     'state': {'worn_by': 'pilot'},
    },
    {'sim_id': 'manual',
     'name': 'flight manual',
     'aliases': ['manual', 'book', 'handbook'],
     'materials': ['paper'],
     'mass_g': 300,
     'zone': 'cockpit',
    },
    {'sim_id': 'flightbag',
     'name': 'flight bag',
     'aliases': ['flightbag'],
     'materials': ['leather'],
     'mass_g': 1400,
     'zone': 'cockpit',
     'state': {'container': True},
    },
    {'sim_id': 'flashlight',
     'name': 'flashlight',
     'aliases': ['torch', 'light'],
     'materials': ['plastic'],
     'mass_g': 250,
     'in': 'flightbag',
     'state': {'powered': True},
    },
    {'sim_id': 'fueltester',
     'name': 'fuel tester',
     'aliases': ['tester', 'sump cup'],
     'materials': ['plastic'],
     'mass_g': 60,
     'in': 'flightbag',
    },
    {'sim_id': 'chart',
     'name': 'sectional chart',
     'aliases': ['chart', 'map'],
     'materials': ['paper'],
     'mass_g': 80,
     'zone': 'cockpit',
    },
    {'sim_id': 'thermos',
     'name': 'thermos of coffee',
     'aliases': ['thermos', 'coffee'],
     'materials': ['water'],
     'mass_g': 800,
     'zone': 'cockpit',
     'state': {'ident': 'still warm'},
    },
    {'sim_id': 'extinguisher',
     'name': 'fire extinguisher',
     'aliases': ['extinguisher'],
     'materials': ['steel'],
     'mass_g': 1500,
     'zone': 'cockpit',
     'state': {'sealed': True},
    },
    {'sim_id': 'panel',
     'name': 'avionics panel',
     'aliases': ['panel'],
     'materials': ['aluminum'],
     'mass_g': 1800,
     'zone': 'cockpit',
     'state': {'container': True, 'open': False, 'jammed': True, 'fixed': True},
    },
    {'sim_id': 'wire',
     'name': 'coil of copper wire',
     'aliases': ['wire', 'coil'],
     'materials': ['copper_wire'],
     'mass_g': 120,
     'in': 'panel',
    },
    # -------------------- mid_cabin --------------------
    {'sim_id': 'seat',
     'name': 'aircraft seat',
     'aliases': ['seat'],
     'materials': ['steel'],
     'mass_g': 5000,
     'zone': 'mid_cabin',
     'state': {'ident': '11B', 'fixed': True},
     "parts": [
         {'id': 'cover',
          'label': 'cover',
          'material': 'synthetic_fabric',
          'mass_g': 200,
          'attachment': 'stitched',
          'outputs_when_removed': ['loose_fabric']},
         {'id': 'cushion',
          'label': 'cushion',
          'material': 'foam',
          'mass_g': 800,
          'attachment': 'clipped',
          'outputs_when_removed': ['loose_foam']},
         {'id': 'belt',
          'label': 'seatbelt',
          'material': 'nylon_webbing',
          'mass_g': 150,
          'attachment': 'bolted',
          'outputs_when_removed': ['loose_webbing']},
         {'id': 'bolt', 'label': 'bolt', 'material': 'steel', 'mass_g': 30, 'attachment': 'bolted'},
     ],
    },
    {'sim_id': 'seatpocket',
     'name': 'seatback pocket',
     'aliases': ['pocket'],
     'materials': ['synthetic_fabric'],
     'mass_g': 100,
     'in': 'seat',
     'state': {'container': True},
    },
    {'sim_id': 'chocolate',
     'name': 'chocolate bar',
     'aliases': ['chocolate', 'bar', 'ration'],
     'materials': ['chocolate'],
     'mass_g': 100,
     'in': 'seatpocket',
    },
    {'sim_id': 'bin_fwd',
     'name': 'forward overhead bin',
     'aliases': ['bin', 'fwd bin'],
     'materials': ['aluminum'],
     'mass_g': 2500,
     'zone': 'mid_cabin',
     'state': {'ident': 'fwd', 'container': True, 'open': False, 'fixed': True},
    },
    {'sim_id': 'firstaid',
     'name': 'first-aid kit',
     'aliases': ['kit', 'first aid'],
     'materials': ['plastic'],
     'mass_g': 400,
     'in': 'bin_fwd',
     'state': {'container': True, 'open': False},
    },
    {'sim_id': 'bandage',
     'name': 'bandage roll',
     'aliases': ['bandage', 'bandages'],
     'materials': ['cotton_cloth'],
     'mass_g': 150,
     'in': 'firstaid',
    },
    {'sim_id': 'tape',
     'name': 'medical tape',
     'aliases': ['tape'],
     'materials': ['plastic'],
     'mass_g': 60,
     'in': 'firstaid',
    },
    {'sim_id': 'toolroll',
     'name': 'tool roll',
     'aliases': ['tools'],
     'materials': ['cotton_cloth'],
     'mass_g': 500,
     'in': 'bin_fwd',
     'state': {'container': True},
    },
    {'sim_id': 'ducttape',
     'name': 'roll of duct tape',
     'aliases': ['duct tape'],
     'materials': ['plastic'],
     'mass_g': 250,
     'in': 'toolroll',
    },
    {'sim_id': 'safetywire',
     'name': 'spool of safety wire',
     'aliases': ['safety wire', 'spool'],
     'materials': ['copper_wire'],
     'mass_g': 200,
     'in': 'toolroll',
    },
    {'sim_id': 'screwdriver',
     'name': 'screwdriver',
     'materials': ['steel'],
     'mass_g': 180,
     'in': 'toolroll',
     'state': {'leverage': 0.35},
    },
    {'sim_id': 'duffel',
     'name': 'duffel bag',
     'aliases': ['duffel', 'bag', 'luggage'],
     'materials': ['synthetic_fabric'],
     'mass_g': 900,
     'zone': 'mid_cabin',
     'state': {'container': True},
    },
    {'sim_id': 'multitool',
     'name': 'multitool',
     'aliases': ['tool', 'knife'],
     'materials': ['steel'],
     'mass_g': 150,
     'in': 'duffel',
     'state': {'edge': 0.8, 'leverage': 0.5},
    },
    {'sim_id': 'paracord',
     'name': 'length of paracord',
     'aliases': ['paracord', 'cord', 'rope'],
     'materials': ['nylon_webbing'],
     'mass_g': 90,
     'in': 'duffel',
    },
    {'sim_id': 'socks',
     'name': 'wool socks',
     'aliases': ['socks'],
     'materials': ['wool'],
     'mass_g': 150,
     'in': 'duffel',
    },
    {'sim_id': 'masks',
     'name': 'oxygen masks',
     'aliases': ['masks', 'mask'],
     'materials': ['plastic'],
     'mass_g': 400,
     'zone': 'mid_cabin',
     'state': {'fixed': True},
     "parts": [
         {'id': 'cup',
          'label': 'mask cup',
          'material': 'plastic',
          'mass_g': 120,
          'attachment': 'clipped',
          'outputs_when_removed': ['loose_cup']},
         {'id': 'tubing',
          'label': 'tubing',
          'material': 'rubber',
          'mass_g': 180,
          'attachment': 'tied',
          'outputs_when_removed': ['rubber_tubing']},
     ],
    },
    # -------------------- rear_cabin --------------------
    {'sim_id': 'snowdrift',
     'name': 'snowdrift',
     'aliases': ['snow', 'drift'],
     'materials': ['snow'],
     'mass_g': 4000,
     'zone': 'rear_cabin',
     'state': {'fixed': True},
    },
    {'sim_id': 'gloves',
     'name': 'leather gloves',
     'aliases': ['gloves'],
     'materials': ['leather'],
     'mass_g': 300,
     'in': 'snowdrift',
    },
    {'sim_id': 'bin_aft',
     'name': 'aft overhead bin',
     'aliases': ['aft bin'],
     'materials': ['aluminum'],
     'mass_g': 2500,
     'zone': 'rear_cabin',
     'state': {'ident': 'aft', 'container': True, 'open': False, 'jammed': True, 'fixed': True},
    },
    {'sim_id': 'backpack',
     'name': 'backpack',
     'aliases': ['pack', 'rucksack'],
     'materials': ['synthetic_fabric'],
     'mass_g': 700,
     'in': 'bin_aft',
     'state': {'container': True},
    },
    {'sim_id': 'canteen',
     'name': 'canteen of water',
     'aliases': ['canteen', 'flask'],
     'materials': ['water'],
     'mass_g': 600,
     'in': 'backpack',
     'state': {'ident': 'half-full'},
    },
    {'sim_id': 'shirt',
     'name': 'spare shirt',
     'aliases': ['shirt'],
     'materials': ['cotton_cloth'],
     'mass_g': 250,
     'in': 'backpack',
    },
    {'sim_id': 'enginecover',
     'name': 'engine cover',
     'aliases': ['quilted cover'],
     'materials': ['cotton_cloth', 'insulation_batting'],
     'mass_g': 3500,
     'in': 'bin_aft',
    },
    {'sim_id': 'seat2',
     'name': 'aircraft seat',
     'aliases': ['seat'],
     'materials': ['steel'],
     'mass_g': 5000,
     'zone': 'rear_cabin',
     'state': {'ident': '12C', 'fixed': True},
     "parts": [
         {'id': 'cover',
          'label': 'cover',
          'material': 'synthetic_fabric',
          'mass_g': 200,
          'attachment': 'stitched',
          'outputs_when_removed': ['loose_fabric']},
         {'id': 'cushion',
          'label': 'cushion',
          'material': 'foam',
          'mass_g': 800,
          'attachment': 'clipped',
          'outputs_when_removed': ['loose_foam']},
         {'id': 'belt',
          'label': 'seatbelt',
          'material': 'nylon_webbing',
          'mass_g': 150,
          'attachment': 'bolted',
          'outputs_when_removed': ['loose_webbing']},
         {'id': 'bolt', 'label': 'bolt', 'material': 'steel', 'mass_g': 30, 'attachment': 'bolted'},
     ],
    },
    {'sim_id': 'bottle',
     'name': 'whisky bottle',
     'aliases': ['bottle', 'whisky'],
     'materials': ['glass'],
     'mass_g': 500,
     'zone': 'rear_cabin',
    },
    {'sim_id': 'blanket',
     'name': 'wool blanket',
     'aliases': ['blanket', 'wool'],
     'materials': ['wool'],
     'mass_g': 700,
     'zone': 'rear_cabin',
    },
    # -------------------- outside_tail --------------------
    {'sim_id': 'ice',
     'name': 'chunk of ice',
     'aliases': ['ice', 'chunk'],
     'materials': ['ice'],
     'mass_g': 600,
     'zone': 'outside_tail',
    },
    {'sim_id': 'jerrycan',
     'name': 'jerry can',
     'aliases': ['can', 'jerrycan'],
     'materials': ['fuel'],
     'mass_g': 3000,
     'zone': 'outside_tail',
     'state': {'sealed': True},
    },
    {'sim_id': 'oil1',
     'name': 'oil quart',
     'aliases': ['oil'],
     'materials': ['fuel'],
     'mass_g': 950,
     'zone': 'outside_tail',
     'state': {'sealed': True},
    },
    {'sim_id': 'oil2',
     'name': 'oil quart',
     'aliases': ['oil'],
     'materials': ['fuel'],
     'mass_g': 950,
     'zone': 'outside_tail',
     'state': {'sealed': True},
    },
    # -------------------- debris_trail --------------------
    {'sim_id': 'survivalduffel',
     'name': 'torn survival duffel',
     'aliases': ['survival duffel', 'torn duffel', 'survival kit'],
     'materials': ['synthetic_fabric'],
     'mass_g': 1200,
     'zone': 'debris_trail',
     'state': {'container': True},
    },
    {'sim_id': 'ration1',
     'name': 'ration tin',
     'aliases': ['tin', 'rations'],
     'materials': ['rations'],
     'mass_g': 400,
     'in': 'survivalduffel',
     'state': {'sealed': True},
    },
    {'sim_id': 'ration2',
     'name': 'ration tin',
     'aliases': ['tin', 'rations'],
     'materials': ['rations'],
     'mass_g': 400,
     'in': 'survivalduffel',
     'state': {'sealed': True},
    },
    {'sim_id': 'fishingkit',
     'name': 'fishing kit',
     'aliases': ['fishing', 'hooks'],
     'materials': ['plastic'],
     'mass_g': 200,
     'in': 'survivalduffel',
    },
    {'sim_id': 'headnet',
     'name': 'mosquito headnet',
     'aliases': ['headnet', 'net'],
     'materials': ['cotton_cloth'],
     'mass_g': 90,
     'in': 'survivalduffel',
    },
    {'sim_id': 'matchbox',
     'name': 'waterproof matchbox',
     'aliases': ['matchbox', 'matches'],
     'materials': ['plastic'],
     'mass_g': 80,
     'in': 'survivalduffel',
     'state': {'wet': True},
    },
    {'sim_id': 'drift2',
     'name': 'wind-packed drift',
     'aliases': ['packed drift', 'snowbank'],
     'materials': ['snow'],
     'mass_g': 9000,
     'zone': 'debris_trail',
     'state': {'fixed': True},
    },
    {'sim_id': 'hatchet',
     'name': 'snapped hatchet',
     'aliases': ['hatchet', 'axe'],
     'materials': ['steel', 'wood'],
     'mass_g': 1100,
     'in': 'drift2',
     'state': {'edge': 0.5, 'leverage': 0.3, 'broken': True},
    },
    {'sim_id': 'flare1',
     'name': 'flare shell',
     'aliases': ['flare'],
     'materials': ['cardboard'],
     'mass_g': 150,
     'in': 'drift2',
     'state': {'sealed': True},
    },
    {'sim_id': 'mailsack',
     'name': 'mail sack',
     'aliases': ['mailbag', 'sack'],
     'materials': ['cotton_cloth'],
     'mass_g': 2500,
     'zone': 'debris_trail',
     'state': {'container': True},
    },
    {'sim_id': 'letters',
     'name': 'bundle of letters',
     'aliases': ['letters', 'mail'],
     'materials': ['paper'],
     'mass_g': 700,
     'in': 'mailsack',
    },
    {'sim_id': 'twine',
     'name': 'ball of twine',
     'aliases': ['twine'],
     'materials': ['nylon_webbing'],
     'mass_g': 120,
     'in': 'mailsack',
    },
    {'sim_id': 'alusheet',
     'name': 'twisted aluminum sheet',
     'aliases': ['aluminum', 'sheet', 'panel piece'],
     'materials': ['aluminum'],
     'mass_g': 3800,
     'zone': 'debris_trail',
    },
    # -------------------- tail_section --------------------
    {'sim_id': 'tailcone',
     'name': 'crushed tail cone',
     'aliases': ['tail cone', 'cone', 'empennage'],
     'materials': ['aluminum'],
     'mass_g': 60000,
     'zone': 'tail_section',
     'state': {'container': True, 'open': False, 'jammed': True, 'fixed': True},
    },
    {'sim_id': 'sleepingbag',
     'name': 'sleeping bag',
     'aliases': ['bag', 'bedroll'],
     'materials': ['wool'],
     'mass_g': 1500,
     'in': 'tailcone',
     'state': {'fuel_soaked': True},
    },
    {'sim_id': 'snowshoes',
     'name': 'snowshoes',
     'aliases': ['shoes', 'snowshoe'],
     'materials': ['wood', 'nylon_webbing'],
     'mass_g': 1800,
     'in': 'tailcone',
    },
    {'sim_id': 'cargonet',
     'name': 'cargo net',
     'aliases': ['net', 'netting'],
     'materials': ['nylon_webbing'],
     'mass_g': 1100,
     'in': 'tailcone',
    },
    {'sim_id': 'elt',
     'name': 'emergency locator transmitter',
     'aliases': ['elt', 'transmitter', 'beacon'],
     'materials': ['plastic', 'copper_wire'],
     'mass_g': 2000,
     'in': 'tailcone',
     'state': {'ident': 'ELT', 'armed': True, 'antenna': 'sheared'},
    },
    {'sim_id': 'crate',
     'name': 'freight crate',
     'aliases': ['crate'],
     'materials': ['wood'],
     'mass_g': 40000,
     'zone': 'tail_section',
     'state': {'container': True, 'open': False, 'jammed': True, 'fixed': True},
    },
    {'sim_id': 'coffeetin',
     'name': 'coffee tin',
     'materials': ['steel'],
     'mass_g': 900,
     'in': 'crate',
     'state': {'sealed': True},
    },
    {'sim_id': 'flour',
     'name': 'flour sack',
     'aliases': ['flour'],
     'materials': ['rations'],
     'mass_g': 2000,
     'in': 'crate',
    },
    # -------------------- treeline --------------------
    {'sim_id': 'tinder',
     'name': 'dry grass',
     'aliases': ['tinder', 'grass'],
     'materials': ['dry_grass'],
     'mass_g': 40,
     'zone': 'treeline',
    },
    {'sim_id': 'spruce',
     'name': 'spruce tree',
     'aliases': ['spruce', 'tree', 'trees'],
     'materials': ['wood'],
     'mass_g': 200000,
     'zone': 'treeline',
     'state': {'fixed': True},
     "parts": [
         {'id': 'low branch',
          'label': 'low branch',
          'material': 'wood',
          'mass_g': 900,
          'attachment': 'grown',
          'outputs_when_removed': ['loose_branch']},
         {'id': 'bough',
          'label': 'bough',
          'material': 'wood',
          'mass_g': 2500,
          'attachment': 'grown',
          'outputs_when_removed': ['loose_bough']},
     ],
    },
    {'sim_id': 'deadfall1',
     'name': 'deadfall branch',
     'aliases': ['deadfall', 'branch'],
     'materials': ['wood'],
     'mass_g': 800,
     'zone': 'treeline',
    },
    {'sim_id': 'deadfall2',
     'name': 'deadfall branch',
     'aliases': ['deadfall', 'branch'],
     'materials': ['wood'],
     'mass_g': 800,
     'zone': 'treeline',
    },
    # -------------------- the luggage, the mail and the freight (players-and-kit.md §3) --------------------
    {"sim_id": "suitcase", "name": "soft suitcase", "aliases": ["suitcase", "case", "luggage"], "materials": ["synthetic_fabric"], "mass_g": 900, "in": "bin_aft", "state": {"container": True, "open": False}},
    {"sim_id": "cotton_clothes", "name": "bundle of cotton clothes", "aliases": ["clothes", "shirts", "t-shirts"], "materials": ["cotton_cloth"], "mass_g": 1200, "in": "suitcase", "state": {"covers": ["torso", "arms"], "wind": 0.15}},
    {"sim_id": "towel", "name": "bath towel", "aliases": ["towel"], "materials": ["cotton_cloth"], "mass_g": 500, "in": "suitcase", "state": {"form": "sheet"}},
    {"sim_id": "toiletry_bag", "name": "toiletry bag", "aliases": ["toiletries", "washbag"], "materials": ["plastic"], "mass_g": 150, "in": "suitcase", "state": {"container": True, "open": False}},
    {"sim_id": "floss", "name": "dental floss", "aliases": ["floss"], "materials": ["nylon_webbing"], "mass_g": 15, "in": "toiletry_bag", "state": {"form": "cord"}},
    {"sim_id": "razor", "name": "disposable razor", "aliases": ["razor"], "materials": ["steel", "plastic"], "mass_g": 12, "in": "toiletry_bag", "state": {"form": "blade", "edge": 0.45}},
    {"sim_id": "sanitizer", "name": "bottle of hand sanitizer", "aliases": ["sanitizer", "gel"], "materials": ["alcohol"], "mass_g": 120, "in": "toiletry_bag", "state": {"sealed": True, "form": "vessel"}},
    {"sim_id": "tampons", "name": "box of tampons", "aliases": ["tampons", "tampon"], "materials": ["cotton_cloth"], "mass_g": 60, "in": "toiletry_bag", "state": {"form": "bundle"}},
    {"sim_id": "paperback", "name": "paperback novel", "aliases": ["paperback", "novel", "book"], "materials": ["paper"], "mass_g": 300, "in": "suitcase"},
    {"sim_id": "laptop_bag", "name": "laptop bag", "aliases": ["laptop bag", "satchel"], "materials": ["synthetic_fabric"], "mass_g": 600, "in": "seat", "state": {"container": True, "open": False}},
    {"sim_id": "laptop", "name": "laptop", "aliases": ["computer"], "materials": ["aluminum", "plastic"], "mass_g": 1400, "in": "laptop_bag", "state": {"powered": True, "battery": 40, "form": "slab"}},
    {"sim_id": "cables", "name": "tangle of cables", "aliases": ["cables", "cable", "charger"], "materials": ["copper_wire"], "mass_g": 200, "in": "laptop_bag", "state": {"form": "cord"}},
    {"sim_id": "water_bottle", "name": "steel water bottle", "aliases": ["bottle", "water bottle"], "materials": ["steel"], "mass_g": 300, "in": "laptop_bag", "state": {"container": True, "open": False, "form": "vessel"}},
    {"sim_id": "bottle_water", "name": "water", "aliases": ["drink"], "materials": ["water"], "mass_g": 500, "in": "water_bottle"},
    {"sim_id": "snacks", "name": "bag of trail mix", "aliases": ["snacks", "trail mix", "nuts"], "materials": ["rations"], "mass_g": 200, "in": "laptop_bag"},
    {"sim_id": "hockey_duffel", "name": "hockey duffel", "aliases": ["hockey bag", "gear bag"], "materials": ["synthetic_fabric"], "mass_g": 1500, "in": "drift2", "state": {"container": True, "open": False}},
    {"sim_id": "hockey_stick", "name": "hockey stick", "aliases": ["stick"], "materials": ["wood"], "mass_g": 600, "in": "hockey_duffel", "state": {"form": "rod"}},
    {"sim_id": "hockey_tape", "name": "roll of hockey tape", "aliases": ["hockey tape", "tape roll"], "materials": ["cotton_cloth"], "mass_g": 80, "in": "hockey_duffel", "state": {"form": "cord"}},
    {"sim_id": "hockey_pads", "name": "hockey pads", "aliases": ["pads", "shin pads"], "materials": ["foam", "plastic"], "mass_g": 900, "in": "hockey_duffel", "state": {"covers": ["legs"], "wind": 0.3}},
    {"sim_id": "cooler", "name": "plastic cooler", "aliases": ["cooler", "icebox"], "materials": ["plastic", "foam"], "mass_g": 2500, "in": "drift2", "state": {"container": True, "open": False, "form": "vessel"}},
    {"sim_id": "frozen_fish", "name": "frozen salmon", "aliases": ["fish", "salmon"], "materials": ["fish"], "mass_g": 3000, "in": "cooler", "state": {"temperature_c": -15}},
    {"sim_id": "guitar_case", "name": "guitar case", "aliases": ["case"], "materials": ["plastic"], "mass_g": 2000, "in": "tailcone", "state": {"container": True, "open": False, "form": "slab"}},
    {"sim_id": "guitar", "name": "acoustic guitar", "aliases": ["guitar"], "materials": ["wood"], "mass_g": 1800, "in": "guitar_case", "state": {"form": "block"}, "parts": [{"id": "strings", "label": "strings", "material": "copper_wire", "mass_g": 20, "attachment": "tied", "outputs_when_removed": ["loose_wire"]}, {"id": "neck", "label": "neck", "material": "wood", "mass_g": 500, "attachment": "glued", "outputs_when_removed": ["wood_rod"]}]},
    {"sim_id": "toolbox", "name": "steel toolbox", "aliases": ["toolbox", "tool box"], "materials": ["steel"], "mass_g": 4000, "in": "crate", "state": {"container": True, "open": False}},
    {"sim_id": "pliers", "name": "pliers", "aliases": ["plier"], "materials": ["steel"], "mass_g": 250, "in": "toolbox", "state": {"leverage": 0.4, "form": "bar"}},
    {"sim_id": "hacksaw_blade", "name": "hacksaw blade", "aliases": ["hacksaw", "saw blade", "saw"], "materials": ["steel"], "mass_g": 60, "in": "toolbox", "state": {"form": "blade", "edge": 0.9}},
    {"sim_id": "shear_pins", "name": "box of shear pins", "aliases": ["pins", "shear pins"], "materials": ["steel"], "mass_g": 300, "in": "toolbox"},
    {"sim_id": "dog_food", "name": "sack of dog food", "aliases": ["dog food", "kibble"], "materials": ["rations"], "mass_g": 9000, "in": "crate", "state": {"ident": "kibble"}},
    {"sim_id": "candles", "name": "parcel of candles", "aliases": ["candles", "candle", "parcel"], "materials": ["wax"], "mass_g": 600, "in": "mailsack", "state": {"form": "rod"}},
    {"sim_id": "holt_parcel", "name": "parcel addressed to V. Holt", "aliases": ["holt parcel", "package"], "materials": ["cardboard"], "mass_g": 900, "in": "mailsack", "state": {"container": True, "open": False, "ident": "V. HOLT"}},
    {"sim_id": "holt_gloves", "name": "pair of beaver mitts", "aliases": ["mitts", "beaver mitts"], "materials": ["leather", "wool"], "mass_g": 400, "in": "holt_parcel", "state": {"covers": ["hands"], "wind": 0.8, "fine_work": False}},
]
