#!/usr/bin/env python3
"""render_scenes — the READ artifact (presentation-v3 retrospective, root cause 5: "nothing ever read
the output"). Host, pure, no Evennia. Renders every zone's `look` (same-zone, the survey + the scene
spaces), every object's `examine` (stowed things included — the DR-24 reveal is a player act, this
is the author's view), and every probe's transcript into docs/review/render-<date>.md, for Andrew
to read against the tell/hide rule and the style guide.

  python3 tools/render_scenes.py [scenario] [--out PATH]
"""
import argparse
import datetime as _dt
import importlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "game"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("scenario", nargs="?", default="whiteout")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    base = f"world.scenarios.{a.scenario}"
    content = importlib.import_module(f"{base}.content")
    objects = importlib.import_module(f"{base}.objects").OBJECT_TABLE
    try:
        probes = importlib.import_module(f"{base}.probes").PROBES
        authored = importlib.import_module(f"{base}.authored").AUTHORED
    except ModuleNotFoundError:
        probes, authored = [], None
    from world.sim import presentation
    from world.sim.space import zones as zonemap
    from world.sim.testing.probes import run_probe
    from world.sim.testing.pure_world import PureWorld

    mats = content.load()
    today = _dt.date.today().isoformat()
    out_path = a.out or os.path.join(ROOT, "docs", "review", f"render-{today}.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    L = [f"# Render — {a.scenario} — {today}", "",
         "> Generated by `make render-scenes`. READ it: does each look obey the tell/hide rule (functional "
         "flavour shown, load-bearing things inside containers)? Does each examine name what the thing "
         "*affords*? Do the probe transcripts read as a world answering, never a parser refusing?", ""]

    # --- every zone's look (same-zone render) -------------------------------------------------
    L.append("## Zones — `look`"); L.append("")
    for zid, z in zonemap.all_zones().items():
        w = PureWorld.from_table(objects, actor_zone=zid)
        ents = [w.get(i) for i in w.in_zone(zid) if i != w.actor_id and w.parent(i) is None]
        scene = presentation.compose_scene(ents)
        L += [f"### {zid} — {z.name}", "", f"*{z.look}*", "", scene or "(nothing loose here)", ""]

    # --- every object's examine ---------------------------------------------------------------
    L.append("## Objects — `examine`"); L.append("")
    w = PureWorld.from_table(objects)
    for r in objects:
        ent = w.get(r["sim_id"])
        where = f"in {r['in']}" if "in" in r else r.get("zone", "")
        L.append(f"- **{r['name']}** (`{r['sim_id']}`, {where}): {presentation.describe(ent)}")
    L.append("")

    # --- every probe's transcript ---------------------------------------------------------------
    L.append("## Probes — transcripts"); L.append("")
    for p in probes:
        res = run_probe(p, objects, mats, authored)
        mark = "✅" if res.passed else ("⏳" if p.get("status") != "pass" else "❌")
        L.append(f"### {mark} {p['id']}  ({p.get('zone', '')}; expect {p.get('expect', 'SUCCESS')}; "
                 f"{p.get('status')})")
        L.append(f"*source: {p.get('source', '')}*"); L.append("")
        for st in res.steps:
            L.append(f"    > {st.line}")
            L.append(f"    {st.narration}".replace("\n", "\n    "))
            L.append(f"    [{st.kind} {st.tier}]")
        if not res.passed:
            L.append(f"    -- {res.reason}")
        L.append("")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"rendered → {os.path.relpath(out_path, ROOT)}  ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
